### ISSUE TITLE
ValueError: cannot copy sequence with size 60 to array axis with dimension 1

### ISSUE THREAD

**Issue by SLZWVICTOR** [mdabashar/TAnoGAN#2]
When I run the program, "ValueError: cannot copy sequence with size 60 to array axis with dimension 1" occured. How can I solve this problem?

**Comment by zhongzhili** [comment]
I ran into the same problem

**Comment by izmendi** [comment]
Hello, I am a phd student. First of all, thank you for sharing the code.
And after reading your paper, and trying to run the code, I have the same problem sith the dataset dimension: The error comes from ..\TAnoGAN\nab_dataset.py in unroll(self, data, labels)

     84             un_labels.append(labels.iloc[idx:idx + seq_len])
     85             idx += stride
---> 86         return np.array(un_data), np.array(un_labels)
     87 
ValueError: cannot copy sequence with size 60 to array axis with dimension 1

I also tried to run separatelly "recurrent_models_pyramid.py" and the error message is: "AttributeError: 'tuple' object has no attribute 'size'"

I'm using Windows 10, Python 3.7.9 and Pytorch 1.7.0.

I think that probably the error is with the libs or with the source datafile. I think I'm not using the correct one, otherwise I don't know, I have check almost everything. My source datafile is the one suggested here, in github (https://www.kaggle.com/boltzmannbrain/nab/download) but it doesn't worked.

Any suggestions are welcome, I would really like to get this code up and running
Thanks in advance.

**Comment by mdabashar** [comment]
> 
> 
> When I run the program, "ValueError: cannot copy sequence with size 60 to array axis with dimension 1" occured. How can I solve this problem?

I used a older version of numpy. Updated and the code is working again.

**Comment by mdabashar** [comment]
> 
> 
> I ran into the same problem

I used a older version of numpy. Updated the code and it is working again.

**Comment by mdabashar** [comment]
> 
> 
> Hello, I am a phd student. First of all, thank you for sharing the code.
> And after reading your paper, and trying to run the code, I have the same problem sith the dataset dimension: The error comes from ..\TAnoGAN\nab_dataset.py in unroll(self, data, labels)
> 
> ```
>  84             un_labels.append(labels.iloc[idx:idx + seq_len])
>  85             idx += stride
> ```
> 
> ---> 86 return np.array(un_data), np.array(un_labels)
> 87
> ValueError: cannot copy sequence with size 60 to array axis with dimension 1
> 
> I also tried to run separatelly "recurrent_models_pyramid.py" and the error message is: "AttributeError: 'tuple' object has no attribute 'size'"
> 
> I'm using Windows 10, Python 3.7.9 and Pytorch 1.7.0.
> 
> I think that probably the error is with the libs or with the source datafile. I think I'm not using the correct one, otherwise I don't know, I have check almost everything. My source datafile is the one suggested here, in github (https://www.kaggle.com/boltzmannbrain/nab/download) but it doesn't worked.
> 
> Any suggestions are welcome, I would really like to get this code up and running
> Thanks in advance.

I used a older version of numpy. Updated the code and it is working again.
